#!/usr/bin/env bash
# Rename interfaces based on subnet matching.
set -o pipefail
set -o nounset

function rename {
    local old=$1
    local new=$2
    if [[ $old != $new ]]; then 
        ip link set $old down
        ip link set $old name $new
        ip link set $new up
    fi
}

MAP=$(ip a |grep scope | tr -s ' ' | cut -d ' ' -f3,6)
while read -r network ifname; do
    if [[ $network =~ ^192.168.0. ]]; then
        rename $ifname "en0"
    elif [[ $network =~ ^10.0.0. ]]; then
        rename $ifname "en3"
    elif [[ $network =~ ^10.100.0. ]]; then
        rename $ifname "en1"
    elif [[ $network =~ ^10.200.0. ]]; then
        rename $ifname "en2"
    fi
done <<< "$MAP"
